version: "3.11"

services:

 # database service
  database:
    image: postgres:14-alpine
    container_name: ${DATABASE_HOST}
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      PGDATA: ${DATABASE_PGDATA}
    volumes:
      - ${DATABASE_PGDATA}
    ports:
      - ${DATABASE_PORT}:5432
    restart: always
    networks:
      - custom

networks:
  custom:
    driver: bridge