version: ${APP_VERSION}

services:

 # database service
  database:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      PGDATA: ${DATABASE_PGDATA}
    volumes:
      - ${DATABASE_PGDATA}
    ports:
      - ${DATABASE_PORT}:5432
    restart: always
    networks:
      - custom
    env_file:
      - .env

# application service
  fastapi-app:
    container_name: ${APP_NAME}
    build: .
    command: python run.py
    ports:
      - ${SITE_PORT}:${SITE_PORT}
    depends_on:
      - database
    restart: always
    networks:
      - custom
    env_file:
      - .env

networks:
  custom:
    driver: bridge